DROP DATABASE IF EXISTS CHIP_FRIDGE;
CREATE DATABASE IF NOT EXISTS CHIP_FRIDGE;
USE CHIP_FRIDGE;

CREATE TABLE product (
    id INT AUTO_INCREMENT,
    sensor INT NOT NULL UNIQUE,
    quantity INT NOT NULL,
    expiration_date DATE,
    product_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);